import { useEffect, useState } from 'react'
import { AnalysisService, AnalysisResult } from '../services/AnalysisService'
import { NavFn } from '../app'

export default function ResultsPage({ id, nav }: { id: string; nav: NavFn }) {
  const [data, setData]   = useState<AnalysisResult | null>(null)
  const [error, setError] = useState('')

  useEffect(() => {
    if (!id) { nav('history'); return }
    AnalysisService.getResults(id).then(setData).catch(e => setError(e.message))
  }, [id])

  if (error) return <div className="error-banner">{error}</div>
  if (!data) return <div style={{ padding:'2rem', color:'var(--snx-text-muted)' }}>Loading results...</div>

  const { analysis, llm_report, category_breakdown, temporal_trend } = data

  function printReport() {
    const catRows = category_breakdown.slice(0,10).map(c =>
      `<tr><td>${c.display}</td><td style="text-align:right">${c.count.toLocaleString()}</td><td style="text-align:right">${c.pct}%</td></tr>`
    ).join('')
    const catTable = category_breakdown.length
      ? `<h2>Category Breakdown</h2><table class="cat"><thead><tr><th>Category</th><th style="text-align:right">Count</th><th style="text-align:right">Share</th></tr></thead><tbody>${catRows}</tbody></table>`
      : ''

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Analysis Report — ${analysis.table_name}</title><style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Inter',system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;padding:2.5rem;max-width:920px;margin:auto;color:#0f172a;line-height:1.6;font-size:11pt}
h1{font-size:1.6rem;font-weight:700;letter-spacing:-.02em;margin:0 0 .25rem}
.meta{font-size:.85rem;color:#64748b;margin-bottom:1.5rem;padding-bottom:1rem;border-bottom:1px solid #e2e8f0}
.tiles{display:grid;grid-template-columns:repeat(4,1fr);gap:.75rem;margin-bottom:1.75rem}
.tile{border:1px solid #e2e8f0;border-radius:8px;padding:.75rem 1rem;background:#f8fafc}
.tile-label{font-size:.7rem;text-transform:uppercase;letter-spacing:.05em;color:#64748b;font-weight:600}
.tile-value{font-size:1.25rem;font-weight:700;color:#0f172a;margin-top:.15rem}
.report h2{margin:1.75rem 0 .6rem;font-size:1.05rem;font-weight:700;color:#0f172a;padding-bottom:.4rem;border-bottom:1px solid #e2e8f0}
.report h2:first-child{margin-top:0}
.report h3{margin:1rem 0 .4rem;font-size:.95rem;font-weight:600;color:#1e3a8a}
.report p{margin:.5rem 0}
.report ul,.report ol{padding-left:1.4rem;margin:.5rem 0}
.report li{margin-bottom:.4rem}
.report strong{color:#0f172a;font-weight:600}
table.cat{width:100%;border-collapse:collapse;margin:.5rem 0 1.25rem;font-size:.9rem}
table.cat th{text-align:left;font-weight:600;color:#64748b;font-size:.75rem;text-transform:uppercase;letter-spacing:.04em;padding:.45rem .6rem;border-bottom:1px solid #cbd5e1}
table.cat td{padding:.5rem .6rem;border-bottom:1px solid #e2e8f0}
.footer{margin-top:2rem;padding-top:1rem;border-top:1px solid #e2e8f0;font-size:.7rem;color:#94a3b8;text-align:center}
@media print{body{padding:1rem;font-size:10.5pt}.tiles{break-inside:avoid}.report h2{break-after:avoid}}
</style></head><body>
<h1>Analysis Report — ${analysis.table_name}</h1>
<div class="meta">${analysis.date_from} → ${analysis.date_to}</div>
<div class="tiles">
  <div class="tile"><div class="tile-label">Total Records</div><div class="tile-value">${(analysis.estimated_records||0).toLocaleString()}</div></div>
  <div class="tile"><div class="tile-label">Sampled</div><div class="tile-value">${(analysis.processed_records||0).toLocaleString()}</div></div>
  <div class="tile"><div class="tile-label">Categories</div><div class="tile-value">${category_breakdown.length}</div></div>
  <div class="tile"><div class="tile-label">Months Covered</div><div class="tile-value">${temporal_trend.length}</div></div>
</div>
<div class="report">${llm_report}</div>
${catTable}
<div class="footer">Generated by 1M Data Analyzer · ${new Date().toLocaleString()}</div>
</body></html>`

    const iframe = document.createElement('iframe')
    iframe.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0;visibility:hidden'
    iframe.setAttribute('aria-hidden', 'true')
    document.body.appendChild(iframe)

    const cleanup = () => {
      try { document.body.removeChild(iframe) } catch {}
    }

    iframe.onload = () => {
      try {
        const w = iframe.contentWindow!
        w.focus()
        w.onafterprint = cleanup
        w.print()
      } catch (e) {
        cleanup()
      }
    }

    const doc = iframe.contentDocument || iframe.contentWindow!.document
    doc.open()
    doc.write(html)
    doc.close()

    setTimeout(cleanup, 60000)
  }

  const totalRecords  = analysis.estimated_records || 0
  const sampledCount  = analysis.processed_records || 0
  const sampleRatePct = totalRecords > 0 ? Math.max(0.1, Math.round((sampledCount / totalRecords) * 1000) / 10) : 0
  const peakMonth     = temporal_trend.reduce((max, t) => t.count > (max?.count ?? -1) ? t : max, null as null | { period: string; count: number })
  const trendMax      = temporal_trend.length ? Math.max(...temporal_trend.map(t => t.count)) : 0

  return (
    <div>
      <div className="results-header">
        <div>
          <div className="page-title" style={{ margin:0 }}>Results — {analysis.table_name}</div>
          <div className="page-subtitle">
            {analysis.date_from} → {analysis.date_to}
            {analysis.completed_at ? ` · completed ${analysis.completed_at}` : ''}
          </div>
        </div>
        <div style={{ display:'flex', gap:'0.5rem' }}>
          <button className="btn btn-secondary" onClick={() => nav('history')}>View History</button>
          <button className="btn btn-primary" onClick={printReport}>Download PDF</button>
        </div>
      </div>

      <div className="metric-tiles">
        <div className="metric-tile">
          <div className="metric-tile__label">Total Records</div>
          <div className="metric-tile__value">{totalRecords.toLocaleString()}</div>
          <div className="metric-tile__hint">in selected range</div>
        </div>
        <div className="metric-tile">
          <div className="metric-tile__label">Sampled</div>
          <div className="metric-tile__value">{sampledCount.toLocaleString()}</div>
          <div className="metric-tile__hint">{sampleRatePct}% of total</div>
        </div>
        <div className="metric-tile">
          <div className="metric-tile__label">Categories</div>
          <div className="metric-tile__value">{category_breakdown.length || '—'}</div>
          <div className="metric-tile__hint">
            {category_breakdown[0] ? `top: ${category_breakdown[0].display}` : 'no category field'}
          </div>
        </div>
        <div className="metric-tile">
          <div className="metric-tile__label">Peak Period</div>
          <div className="metric-tile__value">{peakMonth ? peakMonth.count.toLocaleString() : '—'}</div>
          <div className="metric-tile__hint">{peakMonth ? peakMonth.period.substring(0,7) : 'no trend data'}</div>
        </div>
      </div>

      <div className="report-card">
        <div className="report-content" dangerouslySetInnerHTML={{ __html: llm_report }} />
      </div>

      {(category_breakdown.length > 0 || temporal_trend.length > 0) && (
        <div className="results-grid">
          {category_breakdown.length > 0 && (
            <div className="card">
              <div className="results-section-title">Category Breakdown</div>
              {category_breakdown.slice(0,10).map((c,i) => (
                <div key={i} style={{ marginBottom:'0.65rem' }}>
                  <div style={{ display:'flex', justifyContent:'space-between', fontSize:'0.8rem', marginBottom:'0.25rem' }}>
                    <span style={{ fontWeight:500 }}>{c.display}</span>
                    <span style={{ color:'var(--text-muted)' }}>{c.count.toLocaleString()} · {c.pct}%</span>
                  </div>
                  <div className="progress-bar" style={{ height:'0.35rem' }}>
                    <div className="progress-bar__fill" style={{ width:`${c.pct}%` }}/>
                  </div>
                </div>
              ))}
            </div>
          )}
          {temporal_trend.length > 0 && (
            <div className="card">
              <div className="results-section-title">Volume Over Time</div>
              <div style={{ display:'flex', alignItems:'flex-end', gap:'0.4rem', height:'120px', padding:'0.5rem 0' }}>
                {temporal_trend.map((t,i) => (
                  <div key={i} title={`${t.period.substring(0,7)}: ${t.count.toLocaleString()}`} style={{ flex:1, display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'flex-end', height:'100%' }}>
                    <div style={{
                      width:'100%',
                      background:'var(--primary)',
                      height:`${trendMax ? (t.count/trendMax)*100 : 0}%`,
                      borderRadius:'3px 3px 0 0',
                      minHeight:4,
                      transition:'height 200ms ease',
                    }}/>
                  </div>
                ))}
              </div>
              <div style={{ display:'flex', justifyContent:'space-between', fontSize:'0.7rem', color:'var(--text-muted)', marginTop:'0.5rem' }}>
                <span>{temporal_trend[0]?.period.substring(0,7)}</span>
                <span>{temporal_trend[temporal_trend.length-1]?.period.substring(0,7)}</span>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
